# Generated by Django 4.1 on 2024-08-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='profilereference',
            options={'ordering': []},
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(related_name='job_seekers', to='base.skill'),
        ),
    ]
