# Generated by Django 5.1.2 on 2024-10-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_jobseeker_age_jobseeker_salary_recruiter_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='salary',
            new_name='max_salary',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='salary',
            new_name='max_salary',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='profile_type',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='profile_type',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='min_salary',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='min_salary',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
