# Generated by Django 4.1 on 2024-08-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_skill_alter_profilereference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-name']},
        ),
    ]
