# Generated by Django 4.1 on 2024-08-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_jobseeker_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
