# Generated by Django 5.1.2 on 2024-10-19 07:03

from django.db import migrations, models


def set_user_mode(apps, schema_editor):
    JobSeeker = apps.get_model('base', 'JobSeeker')
    Recruiter = apps.get_model('base', 'Recruiter')

    # Set default modes
    JobSeeker.objects.update(user_mode='job_seeker')
    Recruiter.objects.update(user_mode='recruiter')


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0003_rename_salary_jobseeker_max_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='user_mode',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker Mode'), ('recruiter', 'Recruiter Mode')],
                                   default='job_seeker', max_length=20),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='user_mode',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker Mode'), ('recruiter', 'Recruiter Mode')],
                                   default='job_seeker', max_length=20),
        ),
        migrations.RunPython(set_user_mode),
    ]
