# Generated by Django 5.1.2 on 2024-10-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_jobseeker_user_mode_recruiter_user_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='user_mode',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='user_mode',
        ),
    ]
