# Generated by Django 4.1 on 2024-09-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_skill_skill_level_skill_years_of_experience_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-name"],
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["-skill_name__name"]},
        ),
        migrations.RemoveField(
            model_name="skill",
            name="name",
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.skillname",
            ),
            preserve_default=False,
        ),
    ]
