# Generated by Django 4.1 on 2024-07-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_jobseeker_created_jobseeker_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseeker',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='recruiter',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
