# Generated by Django 4.1 on 2024-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_jobseeker_options_alter_recruiter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='profile_title',
            field=models.TextField(default='default profile', max_length=200),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='profile_title',
            field=models.TextField(default='default profile', max_length=200),
        ),
    ]
