# Generated by Django 5.1.2 on 2024-10-19 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='salary',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='salary',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_profiles', to='base.skill'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_profiles', to='base.skill'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='title',
            field=models.CharField(default='default profile', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profiles',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='title',
            field=models.CharField(default='default profile', max_length=200),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profiles',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('match_status', models.CharField(default='pending', max_length=50)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jobseeker')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recruiter')),
            ],
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='matches',
            field=models.ManyToManyField(related_name='job_seekers', through='base.Match', to='base.recruiter'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='matches',
            field=models.ManyToManyField(related_name='recruiters', through='base.Match', to='base.jobseeker'),
        ),
        migrations.DeleteModel(
            name='ProfileReference',
        ),
    ]
