# Generated by Django 5.1.2 on 2025-02-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_profile_user_alter_usersession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='max_salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
