# Generated by Django 5.1.2 on 2025-02-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_profile_max_salary_remove_profile_min_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Declined'), ('F', 'Failed')], default='F', max_length=1),
        ),
    ]
