# Generated by Django 5.1.4 on 2025-01-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_jobseeker_user_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
