# Generated by Django 5.1.2 on 2025-02-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_match_match_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('job_seeker', 'recruiter')},
        ),
    ]
